version: '3'
services:
  java-service:
    build:
      context: ./java-spring-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - my-network
  python-service:
    build:
      context: ./python-translate-api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
          condition: service_completed_successfully
    environment:
      DB_HOST: postgres
      DB_PORT: 6544
      DB_NAME: manga_translation_db
      DB_USER: admin
      DB_PASSWORD: admin1234

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: manga_translation_db
    ports:
      - "6544:5432"
    networks:
      - my-network
    hostname: postgres


  flyway:
    image: flyway/flyway
    volumes:
      - ./data/postgres/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    environment:
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/manga_translation_db
      - FLYWAY_USER=admin
      - FLYWAY_PASSWORD=admin1234
    command: [ "migrate" ]
    networks:
      - my-network


  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 111
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
